project_id = "qgttbaibhmzbmknjlghj"

[functions.analytics]
verify_jwt = false

[functions.secure-delete]
verify_jwt = true

[functions.admin-role-update]
verify_jwt = true

[functions.photon-proxy]
verify_jwt = false