project_id = "qgttbaibhmzbmknjlghj"

[functions.analytics]
verify_jwt = false

[functions.secure-delete]
verify_jwt = true

[functions.admin-role-update]
verify_jwt = true

[functions.photon-proxy]
verify_jwt = false

[functions.instagram-ai-suggestions]
verify_jwt = false

[functions.check-duplicates]
verify_jwt = false

[functions.chat]
verify_jwt = false
